### ISSUE TITLE
USB Backup - Does not create "Your QuikBackup" folder on user`s flash drive.

### ISSUE THREAD

**Issue by djdarien** [djdarien/Quik-Backup#2]
copies original file folder name and its contents.   

SUCCESS SHOULD BE:    USB BACKUP - "Your QuikBackup" created.

**Comment by djdarien** [comment]
Tested today on my flash drive and it was a success.... leaving this issue open

**Comment by pugking9** [comment]
Known issue. No longer seems to be a problem, thought to be caused by leftover proccess created from bad application closing. Fixed by handling Close() event.
